basePath: /
definitions:
  dto.AuthorResponse:
    properties:
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
    type: object
  dto.BookResponse:
    properties:
      author:
        $ref: '#/definitions/dto.AuthorResponse'
      count_page:
        type: integer
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Это Swagger API для Go проекта
  title: My API
  version: "1.0"
paths:
  /api/book:
    get:
      consumes:
      - application/json
      description: Возвращает список всех книг с автором и мета-данными
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.BookResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Получить все книги
      tags:
      - books
swagger: "2.0"
